updates:
  - commit-message:
      include: scope
      prefix: chore
    directory: /parsers
    groups:
      all-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    package-ecosystem: cargo
    schedule:
      interval: weekly
  - commit-message:
      include: scope
      prefix: chore
    directory: /parsers/datamitsu-parsers
    groups:
      all-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    package-ecosystem: cargo
    schedule:
      interval: weekly
  - commit-message:
      include: scope
      prefix: chore
    directory: /docker
    groups:
      all-dependencies:
        patterns:
          - "*"
    labels:
      - dependencies
      - docker
    open-pull-requests-limit: 10
    package-ecosystem: docker
    schedule:
      interval: weekly
  - commit-message:
      include: scope
      prefix: chore
    directory: /parsers
    groups:
      all-dependencies:
        patterns:
          - "*"
    labels: null
    open-pull-requests-limit: 10
    package-ecosystem: docker
    schedule:
      interval: weekly
  - commit-message:
      prefix: ci
    directory: /
    groups:
      all-dependencies:
        patterns:
          - "*"
    labels:
      - dependencies
      - ci
    open-pull-requests-limit: 10
    package-ecosystem: github-actions
    schedule:
      interval: weekly
  - commit-message:
      include: scope
      prefix: chore
    directory: /
    groups:
      all-dependencies:
        patterns:
          - "*"
    labels:
      - dependencies
      - go
    open-pull-requests-limit: 10
    package-ecosystem: gomod
    schedule:
      interval: weekly
  - commit-message:
      include: scope
      prefix: chore
    directory: /
    groups:
      all-dependencies:
        patterns:
          - "*"
    labels:
      - dependencies
      - npm
    open-pull-requests-limit: 10
    package-ecosystem: npm
    schedule:
      interval: weekly
  - commit-message:
      include: scope
      prefix: chore
    directory: /editors/vscode
    groups:
      all-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    package-ecosystem: npm
    schedule:
      interval: weekly
  - commit-message:
      include: scope
      prefix: chore
    directory: /inspector
    groups:
      all-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    package-ecosystem: npm
    schedule:
      interval: weekly
  - commit-message:
      include: scope
      prefix: chore
    directory: /packaging/action
    groups:
      all-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    package-ecosystem: npm
    schedule:
      interval: weekly
  - commit-message:
      include: scope
      prefix: chore
    directory: /packaging/npm/datamitsu
    groups:
      all-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    package-ecosystem: npm
    schedule:
      interval: weekly
  - commit-message:
      include: scope
      prefix: chore
    directory: /programmable-api/js
    groups:
      all-dependencies:
        patterns:
          - "*"
    labels:
      - dependencies
      - npm
    open-pull-requests-limit: 10
    package-ecosystem: npm
    schedule:
      interval: weekly
  - commit-message:
      include: scope
      prefix: chore
    directory: /website
    groups:
      all-dependencies:
        patterns:
          - "*"
    labels:
      - dependencies
      - npm
    open-pull-requests-limit: 10
    package-ecosystem: npm
    schedule:
      interval: weekly
  - commit-message:
      include: scope
      prefix: chore
    directory: /packaging/python
    groups:
      all-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    package-ecosystem: pip
    schedule:
      interval: weekly
version: 2
