title = "Custom Gitleaks configuration"

[extend]
path = ".datamitsu/gitleaks-managed.toml"

# Algolia search-only API key (public, intended for frontend)
[allowlist]
regexTarget = "match"
regexes = ['''074677e081f2ba8b978c240e37a3ce59''']
paths = ['''\.cache/act/''']
