allowBuilds:
  "@shibanet0/datamitsu-config": false
  "@swc/core": false
  core-js: false
  esbuild: false
  sharp: true
audit: true
auditLevel: high
autoInstallPeers: true
enableGlobalVirtualStore: true
enablePrePostScripts: false
hoistPattern: []
ignorePatchFailures: false
minimumReleaseAgeExclude:
  - "@datamitsu/*"
  - "@ovineko/*"
  - "@shibanet0/*"
optimisticRepeatInstall: true
packageExtensions:
  langium:
    dependencies:
      "@chevrotain/regexp-to-ast": "*"
      vscode-jsonrpc: "*"
      vscode-languageserver-protocol: "*"
      vscode-languageserver-types: "*"
packages:
  - programmable-api/js
  - website
resolutionMode: lowest-direct
savePrefix: ""
strictSsl: true
unsafePerm: false
verifyDepsBeforeRun: install
