allowBuilds:
  "@swc/core": false
  "@vscode/vsce-sign": false
  core-js: false
  esbuild: false
  keytar: false
  sharp: true
audit: {}
auditLevel: high
autoInstallPeers: true
blockExoticSubdeps: true
catalog:
  "@shibanet0/datamitsu-config": 0.0.0-unstable.20260811.991fdcd
dangerouslyAllowAllBuilds: false
dedupeDirectDeps: true
dedupePeerDependents: true
enableGlobalVirtualStore: true
enablePrePostScripts: false
engineStrict: true
hoistPattern: []
ignorePatchFailures: false
lockfile: true
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "@datamitsu/*"
  - "@ovineko/*"
  - "@shibanet0/*"
optimisticRepeatInstall: true
overrides:
  "@docusaurus/plugin-ideal-image": 3.10.2
  vscode-jsonrpc: 9.0.1
  vscode-languageserver-protocol: 3.18.2
  vscode-languageserver-types: 3.18.0
packageExtensions:
  langium:
    dependencies:
      "@chevrotain/regexp-to-ast": "*"
      vscode-jsonrpc: "*"
      vscode-languageserver-protocol: "*"
      vscode-languageserver-types: "*"
packageManagerStrict: true
packageManagerStrictVersion: true
packages:
  - packaging/action
  - editors/*
  - programmable-api/js
  - website
  - parsers/datamitsu-parsers
preferFrozenLockfile: true
resolutionMode: lowest-direct
savePrefix: ""
strictDepBuilds: true
strictSsl: true
trustLockfile: true
trustPolicy: no-downgrade
unsafePerm: false
updateNotifier: false
verifyDepsBeforeRun: install
verifyStoreIntegrity: true
