// AUTO-GENERATED by scripts/gen-hashes.ts at release time. Do not edit by hand.
// Maps "<goos>_<goarch>" to the release asset filename and its SHA-256.
// The placeholder below (version 0.0.0, no assets) makes the action refuse to
// install — a real release bakes the version and verified hashes here.
import type { ReleaseAsset } from "./checksums";

export const VERSION = "0.0.0";

export const RELEASES: Record<string, ReleaseAsset> = {};
