package parsermanager

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"sync/atomic"
	"testing"

	"github.com/datamitsu/datamitsu/internal/config"
)

// echoWASM reads the committed echo.wasm fixture. It is the real Rust→WASM module
// (regenerated by the `build:parsers` task) so the test exercises the actual ABI
// without requiring cargo at `go test` time.
func echoWASM(t *testing.T) []byte {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("testdata", "echo.wasm"))
	if err != nil {
		t.Fatalf("read echo.wasm fixture: %v", err)
	}
	return b
}

func TestRuntime_EchoRoundTrips(t *testing.T) {
	ctx := context.Background()
	rt, err := NewRuntime(ctx, echoWASM(t))
	if err != nil {
		t.Fatalf("NewRuntime() error = %v", err)
	}
	t.Cleanup(func() { _ = rt.Close(ctx) })

	diags, err := rt.Parse(ctx, "echo", []byte("hello world"), nil, 0)
	if err != nil {
		t.Fatalf("Parse() error = %v", err)
	}
	if len(diags) != 1 {
		t.Fatalf("Parse() returned %d diagnostics, want 1", len(diags))
	}
	if diags[0].Message != "hello world" {
		t.Fatalf("message = %q, want %q", diags[0].Message, "hello world")
	}
	// Only message + code are emitted by echo; every other field stays nil to
	// model the nullable contract ("tool didn't provide this").
	if diags[0].Code == nil || *diags[0].Code != "0" {
		t.Fatalf("code = %v, want pointer to %q", diags[0].Code, "0")
	}
	if diags[0].Row != nil || diags[0].Col != nil || diags[0].Severity != nil || diags[0].Source != nil {
		t.Fatalf("unprovided fields must be nil, got %+v", diags[0])
	}
}

func TestRuntime_EchoPreservesMultilineAndExitCode(t *testing.T) {
	ctx := context.Background()
	rt, err := NewRuntime(ctx, echoWASM(t))
	if err != nil {
		t.Fatalf("NewRuntime() error = %v", err)
	}
	t.Cleanup(func() { _ = rt.Close(ctx) })

	// Multiline input must arrive whole (host does not line-split).
	diags, err := rt.Parse(ctx, "echo", []byte("line1\nline2"), []byte("ignored"), 2)
	if err != nil {
		t.Fatalf("Parse() error = %v", err)
	}
	if len(diags) != 1 || diags[0].Message != "line1\nline2" {
		t.Fatalf("multiline message not preserved: %+v", diags)
	}
	if diags[0].Code == nil || *diags[0].Code != "2" {
		t.Fatalf("exit code not threaded into code: %v", diags[0].Code)
	}
}

func TestRuntime_UnknownToolReturnsEmpty(t *testing.T) {
	ctx := context.Background()
	rt, err := NewRuntime(ctx, echoWASM(t))
	if err != nil {
		t.Fatalf("NewRuntime() error = %v", err)
	}
	t.Cleanup(func() { _ = rt.Close(ctx) })

	diags, err := rt.Parse(ctx, "not-a-real-parser", []byte("x"), nil, 1)
	if err != nil {
		t.Fatalf("Parse() error = %v", err)
	}
	if len(diags) != 0 {
		t.Fatalf("unknown tool should yield no diagnostics, got %+v", diags)
	}
}

func TestRuntime_DescribeReportsEchoCapability(t *testing.T) {
	ctx := context.Background()
	rt, err := NewRuntime(ctx, echoWASM(t))
	if err != nil {
		t.Fatalf("NewRuntime() error = %v", err)
	}
	t.Cleanup(func() { _ = rt.Close(ctx) })

	caps, err := rt.Describe(ctx)
	if err != nil {
		t.Fatalf("Describe() error = %v", err)
	}
	if caps.SchemaVersion != 1 {
		t.Errorf("schemaVersion = %d, want 1", caps.SchemaVersion)
	}
	if caps.Module != "datamitsu-parsers" {
		t.Errorf("module = %q, want %q", caps.Module, "datamitsu-parsers")
	}
	// Version is build-injected (or the crate fallback) — never empty.
	if caps.Version == "" {
		t.Error("version must be non-empty (build-injected or crate fallback)")
	}
	if len(caps.Tools) != 1 || caps.Tools[0].Name != "echo" {
		t.Fatalf("tools = %+v, want exactly [echo]", caps.Tools)
	}
}

func TestRuntime_MalformedModuleFails(t *testing.T) {
	ctx := context.Background()
	_, err := NewRuntime(ctx, []byte("\x00asm not a real module"))
	if err == nil {
		t.Fatal("expected error instantiating a malformed module, got nil")
	}
	if !strings.Contains(err.Error(), "instantiate parser module") {
		t.Fatalf("error = %v, want it to mention instantiate", err)
	}
}

// TestParseOutput_EndToEnd is the Task-7 dog-food in test form: the Manager
// downloads the echo parser into a content-addressed store (httptest server),
// verifies its SHA-256, loads it into wazero, and gets the fixed echo answer.
func TestParseOutput_EndToEnd(t *testing.T) {
	t.Setenv("DATAMITSU_PARSERS_DIR", t.TempDir())
	ctx := context.Background()

	wasm := echoWASM(t)
	srv, hits := serveWASM(t, wasm)

	m := New(config.MapOfParsers{
		"echo": {URL: srv.URL, Hash: sha256Hex(wasm)},
	})

	diags, err := m.ParseOutput(ctx, "echo", "echo", []byte("end to end"), nil, 0)
	if err != nil {
		t.Fatalf("ParseOutput() error = %v", err)
	}
	if len(diags) != 1 || diags[0].Message != "end to end" {
		t.Fatalf("ParseOutput() = %+v, want one diagnostic echoing input", diags)
	}

	// A second invocation must reuse the stored module — no second download.
	if _, err := m.ParseOutput(ctx, "echo", "echo", []byte("again"), nil, 0); err != nil {
		t.Fatalf("second ParseOutput() error = %v", err)
	}
	if n := atomic.LoadInt64(hits); n != 1 {
		t.Fatalf("server hits = %d, want 1 (download must be deduplicated)", n)
	}
}
