package parsermanager

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"sync/atomic"
	"testing"

	"github.com/datamitsu/datamitsu/internal/config"
)

// echoWASM reads the committed echo.wasm fixture. It is the real Rust→WASM module
// (regenerated by the `build:parsers` task) so the test exercises the actual ABI
// without requiring cargo at `go test` time.
func echoWASM(t *testing.T) []byte {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("testdata", "echo.wasm"))
	if err != nil {
		t.Fatalf("read echo.wasm fixture: %v", err)
	}
	return b
}

func TestRuntime_EchoRoundTrips(t *testing.T) {
	ctx := context.Background()
	rt, err := NewRuntime(ctx, echoWASM(t))
	if err != nil {
		t.Fatalf("NewRuntime() error = %v", err)
	}
	t.Cleanup(func() { _ = rt.Close(ctx) })

	diags, err := rt.Parse(ctx, "echo", []byte("hello world"), nil, 0)
	if err != nil {
		t.Fatalf("Parse() error = %v", err)
	}
	if len(diags) != 1 {
		t.Fatalf("Parse() returned %d diagnostics, want 1", len(diags))
	}
	if diags[0].Message != "hello world" {
		t.Fatalf("message = %q, want %q", diags[0].Message, "hello world")
	}
	// Only message + code are emitted by echo; every other field stays nil to
	// model the nullable contract ("tool didn't provide this").
	if diags[0].Code == nil || *diags[0].Code != "0" {
		t.Fatalf("code = %v, want pointer to %q", diags[0].Code, "0")
	}
	if diags[0].Row != nil || diags[0].Col != nil || diags[0].Severity != nil || diags[0].Source != nil {
		t.Fatalf("unprovided fields must be nil, got %+v", diags[0])
	}
}

func TestRuntime_EchoPreservesMultilineAndExitCode(t *testing.T) {
	ctx := context.Background()
	rt, err := NewRuntime(ctx, echoWASM(t))
	if err != nil {
		t.Fatalf("NewRuntime() error = %v", err)
	}
	t.Cleanup(func() { _ = rt.Close(ctx) })

	// Multiline input must arrive whole (host does not line-split).
	diags, err := rt.Parse(ctx, "echo", []byte("line1\nline2"), []byte("ignored"), 2)
	if err != nil {
		t.Fatalf("Parse() error = %v", err)
	}
	if len(diags) != 1 || diags[0].Message != "line1\nline2" {
		t.Fatalf("multiline message not preserved: %+v", diags)
	}
	if diags[0].Code == nil || *diags[0].Code != "2" {
		t.Fatalf("exit code not threaded into code: %v", diags[0].Code)
	}
}

func TestRuntime_UnknownToolReturnsEmpty(t *testing.T) {
	ctx := context.Background()
	rt, err := NewRuntime(ctx, echoWASM(t))
	if err != nil {
		t.Fatalf("NewRuntime() error = %v", err)
	}
	t.Cleanup(func() { _ = rt.Close(ctx) })

	diags, err := rt.Parse(ctx, "not-a-real-parser", []byte("x"), nil, 1)
	if err != nil {
		t.Fatalf("Parse() error = %v", err)
	}
	if len(diags) != 0 {
		t.Fatalf("unknown tool should yield no diagnostics, got %+v", diags)
	}
}

func TestRuntime_DescribeReportsCapabilities(t *testing.T) {
	ctx := context.Background()
	rt, err := NewRuntime(ctx, echoWASM(t))
	if err != nil {
		t.Fatalf("NewRuntime() error = %v", err)
	}
	t.Cleanup(func() { _ = rt.Close(ctx) })

	caps, err := rt.Describe(ctx)
	if err != nil {
		t.Fatalf("Describe() error = %v", err)
	}
	if caps.SchemaVersion != 1 {
		t.Errorf("schemaVersion = %d, want 1", caps.SchemaVersion)
	}
	if caps.Module != "datamitsu-parsers" {
		t.Errorf("module = %q, want %q", caps.Module, "datamitsu-parsers")
	}
	// Version is build-injected (or the crate fallback) — never empty.
	if caps.Version == "" {
		t.Error("version must be non-empty (build-injected or crate fallback)")
	}
	got := make(map[string]bool, len(caps.Tools))
	for _, tc := range caps.Tools {
		got[tc.Name] = true
	}
	for _, want := range []string{"echo", "yamllint", "dotenv_linter", "cue_fmt"} {
		if !got[want] {
			t.Errorf("describe missing tool %q; got %+v", want, caps.Tools)
		}
	}
}

// TestRuntime_YamllintParsesRealOutput is the cross-language end-to-end check:
// real yamllint --format parsable output through the actual WASM parser yields
// structured, nullable diagnostics in Go.
func TestRuntime_YamllintParsesRealOutput(t *testing.T) {
	ctx := context.Background()
	rt, err := NewRuntime(ctx, echoWASM(t))
	if err != nil {
		t.Fatalf("NewRuntime() error = %v", err)
	}
	t.Cleanup(func() { _ = rt.Close(ctx) })

	out := []byte("stdin:3:1: [error] too many blank lines (3 > 0) (empty-lines)\n" +
		"stdin:10:5: [warning] line too long (90 > 80 characters) (line-length)\n")
	diags, err := rt.Parse(ctx, "yamllint", out, nil, 1)
	if err != nil {
		t.Fatalf("Parse(yamllint) error = %v", err)
	}
	if len(diags) != 2 {
		t.Fatalf("got %d diagnostics, want 2: %+v", len(diags), diags)
	}
	d := diags[0]
	if d.Message != "too many blank lines (3 > 0)" {
		t.Errorf("message = %q", d.Message)
	}
	if d.Row == nil || *d.Row != 3 || d.Col == nil || *d.Col != 1 {
		t.Errorf("row/col = %v/%v, want 3/1", d.Row, d.Col)
	}
	if d.Severity == nil || *d.Severity != 1 {
		t.Errorf("severity = %v, want 1 (error)", d.Severity)
	}
	if d.Code == nil || *d.Code != "empty-lines" {
		t.Errorf("code = %v, want empty-lines", d.Code)
	}
}

func TestRuntime_MalformedModuleFails(t *testing.T) {
	ctx := context.Background()
	_, err := NewRuntime(ctx, []byte("\x00asm not a real module"))
	if err == nil {
		t.Fatal("expected error instantiating a malformed module, got nil")
	}
	if !strings.Contains(err.Error(), "instantiate parser module") {
		t.Fatalf("error = %v, want it to mention instantiate", err)
	}
}

// TestParseOutput_EndToEnd is the Task-7 dog-food in test form: the Manager
// downloads the echo parser into a content-addressed store (httptest server),
// verifies its SHA-256, loads it into wazero, and gets the fixed echo answer.
func TestParseOutput_EndToEnd(t *testing.T) {
	t.Setenv("DATAMITSU_PARSERS_DIR", t.TempDir())
	ctx := context.Background()

	wasm := echoWASM(t)
	srv, hits := serveWASM(t, wasm)

	m := New(config.MapOfParsers{
		"echo": {URL: srv.URL, Hash: sha256Hex(wasm)},
	})

	diags, err := m.ParseOutput(ctx, "echo", []byte("end to end"), nil, 0)
	if err != nil {
		t.Fatalf("ParseOutput() error = %v", err)
	}
	if len(diags) != 1 || diags[0].Message != "end to end" {
		t.Fatalf("ParseOutput() = %+v, want one diagnostic echoing input", diags)
	}

	// A second invocation must reuse the stored module — no second download.
	if _, err := m.ParseOutput(ctx, "echo", []byte("again"), nil, 0); err != nil {
		t.Fatalf("second ParseOutput() error = %v", err)
	}
	if n := atomic.LoadInt64(hits); n != 1 {
		t.Fatalf("server hits = %d, want 1 (download must be deduplicated)", n)
	}
}
