import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { parseChecksums, platformAssets, type ReleaseAsset } from "../src/checksums";

const ACTION_DIR = join(import.meta.dirname, "..");
const REPO_ROOT = join(ACTION_DIR, "..", "..");

const version = (process.env.VERSION ?? "").replace(/^v/, "");
if (version === "") {
  throw new Error("VERSION env var is required (e.g. v0.1.5)");
}

const checksumsPath = process.env.CHECKSUMS_FILE ?? join(REPO_ROOT, "dist", "checksums.txt");
const checksums = parseChecksums(readFileSync(checksumsPath, "utf8"));

const releases: Record<string, ReleaseAsset> = {};
for (const { file, key } of platformAssets(version)) {
  const sha256 = checksums.get(file);
  if (sha256 === undefined) {
    console.warn(`⚠️  no checksum for ${file} — skipping ${key}`);
  } else {
    releases[key] = { file, sha256 };
  }
}

if (Object.keys(releases).length === 0) {
  throw new Error(`no datamitsu release assets for ${version} in ${checksumsPath}`);
}

const entries = Object.entries(releases)
  .map(
    ([key, { file, sha256 }]) =>
      `  ${JSON.stringify(key)}: { file: ${JSON.stringify(file)}, sha256: ${JSON.stringify(sha256)} },`,
  )
  .join("\n");

const body = `// AUTO-GENERATED by scripts/gen-hashes.ts at release time. Do not edit by hand.
// Maps "<goos>_<goarch>" to the release asset filename and its SHA-256.
import type { ReleaseAsset } from "./checksums";

export const VERSION = ${JSON.stringify(version)};

export const RELEASES: Record<string, ReleaseAsset> = {
${entries}
};
`;

writeFileSync(join(ACTION_DIR, "src", "generated.ts"), body);
console.log(`✓ wrote src/generated.ts for ${version} (${Object.keys(releases).length} platforms)`);
