[project]
name = "datamitsu"
version = "0.0.0"
description = "Configuration management and binary distribution tool. JavaScript-configurable tool orchestration written in Go."
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "Alexander Svinarev", email = "shibanet0@gmail.com" }]
keywords = [
  "binary",
  "config",
  "datamitsu",
  "golangci-lint",
  "lefthook",
  "linter",
  "tools"
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: Software Development :: Quality Assurance",
]
requires-python = ">=3.8"

[project.urls]
Documentation = "https://datamitsu.com"
Homepage = "https://github.com/datamitsu/datamitsu"
Issues = "https://github.com/datamitsu/datamitsu/issues"
Repository = "https://github.com/datamitsu/datamitsu"

[project.scripts]
datamitsu = "datamitsu.main:main"
dm = "datamitsu.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["datamitsu"]
artifacts = ["datamitsu"]

[tool.hatch.build.targets.sdist]
include = [
  "datamitsu/",
]

[tool.hatch.build.hooks.custom]
path = "hatch_build.py"

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple/"
default = true
