package dockerfile

import (
	"fmt"
	"path"
	"sort"
	"strconv"
	"strings"

	"github.com/datamitsu/datamitsu/internal/config"
)

// RenderOptions carries the non-plan inputs to rendering: the base image and its
// (optional) digest, plus the structural conventions of the generated image.
// Labels and entrypoint are inputs (not hardcoded) so each wrapper repo supplies
// its own identity via the committed generate invocation.
type RenderOptions struct {
	BaseImage      string            // e.g. "ghcr.io/datamitsu/datamitsu:0.0.19"
	Digest         string            // "sha256:..."; empty means unpinned
	UnpinnedReason string            // explains, in a comment, why Digest is empty
	ConfigSource   string            // build-context path COPYed in (default "datamitsu.config.js")
	WorkDir        string            // config dir inside the image
	StoreRoot      string            // DATAMITSU_CACHE_DIR value
	User           string            // final (and build) image user
	Labels         map[string]string // OCI labels for the final image
	Entrypoint     []string          // final ENTRYPOINT; defaulted when nil
	Cmd            []string          // final CMD
	NoVerify       bool              // disable in-stage version checks (verification is on by default)
}

// DefaultRenderOptions returns the conventions used for a datamitsu-config
// wrapper image. Callers set BaseImage/Digest (and may override the rest).
func DefaultRenderOptions() RenderOptions {
	return RenderOptions{
		ConfigSource: "datamitsu.config.js",
		WorkDir:      "/opt/datamitsu-config",
		StoreRoot:    "/dm",
		User:         "datamitsu",
		Cmd:          []string{"--help"},
	}
}

// configImagePath is the in-image path of the COPYed config file.
func (o RenderOptions) configImagePath() string {
	return path.Join(o.WorkDir, path.Base(o.ConfigSource))
}

// storeAbs returns the absolute in-image path of a store subtree.
func (o RenderOptions) storeAbs(subtree string) string {
	return path.Join(o.StoreRoot, "store", subtree)
}

// Render produces the full Dockerfile text for plan + opts. It is deterministic:
// the same plan and options always yield byte-identical output.
func Render(plan Plan, opts RenderOptions) string {
	var b strings.Builder

	writeHeader(&b, opts)
	writeBaseStage(&b, opts)
	writeRuntimeStages(&b, plan, opts)
	writeRuntimeAppStages(&b, plan, opts)
	writeBinaryStages(&b, plan, opts)
	writeFinalStage(&b, plan, opts)

	return b.String()
}

func writeHeader(b *strings.Builder, opts RenderOptions) {
	b.WriteString("# syntax=docker/dockerfile:1\n")
	b.WriteString("# GENERATED by `datamitsu devtools dockerfile` — DO NOT EDIT.\n")
	b.WriteString("# Regenerate after changing the config or bumping the datamitsu version.\n")
	if opts.Digest != "" {
		fmt.Fprintf(b, "# Base image %s pinned by digest %s\n", opts.BaseImage, opts.Digest)
	} else {
		reason := opts.UnpinnedReason
		if reason == "" {
			reason = "digest could not be resolved"
		}
		fmt.Fprintf(b, "# WARNING: base image %s is NOT pinned by digest (%s).\n", opts.BaseImage, reason)
	}
	b.WriteString("\n")
}

func writeBaseStage(b *strings.Builder, opts RenderOptions) {
	from := opts.BaseImage
	if opts.Digest != "" {
		from += "@" + opts.Digest
	}
	b.WriteString("# Shared base: datamitsu binary + the wrapper config; writable store dir.\n")
	fmt.Fprintf(b, "FROM %s AS dm-base\n", from)
	b.WriteString("USER root\n")
	fmt.Fprintf(b, "RUN mkdir -p %s %s && chown -R %s:%s %s %s\n",
		opts.StoreRoot, opts.WorkDir, opts.User, opts.User, opts.StoreRoot, opts.WorkDir)
	fmt.Fprintf(b, "USER %s\n", opts.User)
	fmt.Fprintf(b, "ENV DATAMITSU_CACHE_DIR=%s\n", opts.StoreRoot)
	fmt.Fprintf(b, "WORKDIR %s\n", opts.WorkDir)
	fmt.Fprintf(b, "COPY --chown=%s:%s %s ./\n", opts.User, opts.User, opts.ConfigSource)
	// A git root is required for config discovery during install (matches the
	// hand-written wrapper's `git init` trick).
	b.WriteString("RUN git init -q .\n\n")
}

// installCmd is the RUN command a builder stage uses to install one target.
func (o RenderOptions) installCmd(args ...string) string {
	parts := append([]string{"datamitsu", "--config", o.configImagePath(), "install"}, args...)
	return "RUN " + strings.Join(parts, " ")
}

func writeRuntimeStages(b *strings.Builder, plan Plan, opts RenderOptions) {
	if len(plan.RuntimeStages) == 0 {
		return
	}
	b.WriteString("# --- Runtime stages (one per managed runtime) ---\n")
	for _, rt := range plan.RuntimeStages {
		fmt.Fprintf(b, "FROM dm-base AS %s\n", stageName("rt-", rt.Name))
		fmt.Fprintf(b, "%s\n\n", opts.installCmd("--runtime", rt.Name))
	}
}

func writeRuntimeAppStages(b *strings.Builder, plan Plan, opts RenderOptions) {
	if len(plan.RuntimeAppStages) == 0 {
		return
	}
	b.WriteString("# --- App stages (runtime-managed; inherit their runtime stage) ---\n")
	for _, ts := range plan.RuntimeAppStages {
		fmt.Fprintf(b, "FROM %s AS %s\n", stageName("rt-", ts.Runtime), stageName("app-", ts.App))
		fmt.Fprintf(b, "%s\n\n", opts.installCmd(opts.appInstallArgs(ts.App)...))
	}
}

func writeBinaryStages(b *strings.Builder, plan Plan, opts RenderOptions) {
	if len(plan.BinaryStages) == 0 {
		return
	}
	b.WriteString("# --- Binary stages (one per downloaded binary) ---\n")
	for _, bs := range plan.BinaryStages {
		fmt.Fprintf(b, "FROM dm-base AS %s\n", stageName("app-", bs.App))
		fmt.Fprintf(b, "%s\n\n", opts.installCmd(opts.appInstallArgs(bs.App)...))
	}
}

// appInstallArgs is the install argument list for one app. `install` verifies by
// default, so plain `install <app>` runs the version check in-stage; --no-verify
// is appended only when the caller opts out.
func (o RenderOptions) appInstallArgs(app string) []string {
	if o.NoVerify {
		return []string{app, "--no-verify"}
	}
	return []string{app}
}

func writeFinalStage(b *strings.Builder, plan Plan, opts RenderOptions) {
	b.WriteString("# --- Final image: assemble per-app store layers ---\n")
	b.WriteString("FROM dm-base AS final\n")
	writeLabels(b, opts.Labels)

	// Runtime store subtrees (skip kinds whose runtime is build-only, e.g. go).
	for _, rt := range plan.RuntimeStages {
		if !runtimeCopiedToFinal(rt.Kind) {
			continue
		}
		writeCopy(b, stageName("rt-", rt.Name), opts.storeAbs(runtimeSubtree(rt.Name)))
	}

	// Per-app store subtrees; uv apps also carry the managed CPython they used.
	for _, ts := range plan.RuntimeAppStages {
		stage := stageName("app-", ts.App)
		writeCopy(b, stage, opts.storeAbs(appEnvSubtree(ts.Kind, ts.App)))
		if ts.Kind == config.RuntimeKindUV {
			writeCopy(b, stage, opts.storeAbs(uvPythonSubtree))
		}
	}

	// Binary store subtrees.
	for _, bs := range plan.BinaryStages {
		writeCopy(b, stageName("app-", bs.App), opts.storeAbs(binaryAppSubtree(bs.App)))
	}

	fmt.Fprintf(b, "USER %s\n", opts.User)
	b.WriteString("WORKDIR /workspace\n")

	entrypoint := opts.Entrypoint
	if entrypoint == nil {
		entrypoint = []string{"/usr/local/bin/datamitsu", "--before-config", opts.configImagePath()}
	}
	fmt.Fprintf(b, "ENTRYPOINT %s\n", jsonArray(entrypoint))
	if len(opts.Cmd) > 0 {
		fmt.Fprintf(b, "CMD %s\n", jsonArray(opts.Cmd))
	}
}

func writeLabels(b *strings.Builder, labels map[string]string) {
	if len(labels) == 0 {
		return
	}
	keys := make([]string, 0, len(labels))
	for k := range labels {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(b, "LABEL %s=%s\n", k, strconv.Quote(labels[k]))
	}
}

func writeCopy(b *strings.Builder, fromStage, abs string) {
	fmt.Fprintf(b, "COPY --link --from=%s %s %s\n", fromStage, abs, abs)
}

// jsonArray renders a string slice as a JSON array for exec-form instructions.
// strconv.Quote yields JSON-compatible quoting for the ASCII paths/flags used in
// entrypoints, avoiding an encoding/json dependency for this hot, simple path.
func jsonArray(items []string) string {
	quoted := make([]string, len(items))
	for i, s := range items {
		quoted[i] = strconv.Quote(s)
	}
	return "[" + strings.Join(quoted, ",") + "]"
}

// stageName builds a Docker-safe stage name (lowercase, [a-z0-9_.-]) from a
// prefix and a raw app/runtime name.
func stageName(prefix, raw string) string {
	var b strings.Builder
	b.WriteString(prefix)
	for _, r := range strings.ToLower(raw) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '_', r == '.', r == '-':
			b.WriteRune(r)
		default:
			b.WriteRune('-')
		}
	}
	return b.String()
}
