package dockerfile

import (
	"fmt"
	"path"
	"sort"
	"strconv"
	"strings"

	"github.com/datamitsu/datamitsu/internal/config"
)

// RenderOptions carries the non-plan inputs to rendering: the base image and its
// (optional) digest, plus the structural conventions of the generated image.
// Labels and entrypoint are inputs (not hardcoded) so each wrapper repo supplies
// its own identity via the committed generate invocation.
type RenderOptions struct {
	BaseImage      string            // e.g. "ghcr.io/datamitsu/datamitsu:0.0.19"
	Digest         string            // "sha256:..."; empty means unpinned
	UnpinnedReason string            // explains, in a comment, why Digest is empty
	ConfigSource   string            // build-context path COPYed in (default "datamitsu.config.js")
	WorkDir        string            // config dir inside the image
	StoreRoot      string            // DATAMITSU_CACHE_DIR value
	User           string            // final (and build) image user
	Labels         map[string]string // OCI labels for the final image
	Args           map[string]string // final-stage build ARGs declared before ENV (value "" = bare ARG)
	Env            map[string]string // ENV vars baked into the final image
	BuildArgs      map[string]string // ARG→ENV promoted in the dm-build stage so install stages inherit them (value "" = bare ARG)
	Entrypoint     []string          // final ENTRYPOINT; defaulted when nil
	Cmd            []string          // final CMD
	NoVerify       bool              // disable in-stage version checks (verification is on by default)
}

// DefaultRenderOptions returns the conventions used for a datamitsu-config
// wrapper image. Callers set BaseImage/Digest (and may override the rest).
func DefaultRenderOptions() RenderOptions {
	return RenderOptions{
		ConfigSource: "datamitsu.config.js",
		WorkDir:      "/opt/datamitsu-config",
		StoreRoot:    "/dm",
		User:         "datamitsu",
		Cmd:          []string{"--help"},
	}
}

// configImagePath is the in-image path of the COPYed config file.
func (o RenderOptions) configImagePath() string {
	return path.Join(o.WorkDir, path.Base(o.ConfigSource))
}

// storeAbs returns the absolute in-image path of a store subtree.
func (o RenderOptions) storeAbs(subtree string) string {
	return path.Join(o.StoreRoot, "store", subtree)
}

// Render produces the full Dockerfile text for plan + opts. It is deterministic:
// the same plan and options always yield byte-identical output.
func Render(plan Plan, opts RenderOptions) string {
	var b strings.Builder

	writeHeader(&b, opts)
	writeBaseStage(&b, opts)
	writeBuildStage(&b, opts)
	writeConfigSplitStage(&b, opts)
	writeRuntimeStages(&b, plan, opts)
	writeRuntimeAppStages(&b, plan, opts)
	writeBinaryStages(&b, plan, opts)
	writeFinalStage(&b, plan, opts)

	return b.String()
}

func writeHeader(b *strings.Builder, opts RenderOptions) {
	b.WriteString("# syntax=docker/dockerfile:1\n")
	b.WriteString("# GENERATED by `datamitsu devtools dockerfile` — DO NOT EDIT.\n")
	b.WriteString("# Regenerate after changing the config or bumping the datamitsu version.\n")
	if opts.Digest != "" {
		fmt.Fprintf(b, "# Base image %s pinned by digest %s\n", opts.BaseImage, opts.Digest)
	} else {
		reason := opts.UnpinnedReason
		if reason == "" {
			reason = "digest could not be resolved"
		}
		fmt.Fprintf(b, "# WARNING: base image %s is NOT pinned by digest (%s).\n", opts.BaseImage, reason)
	}
	b.WriteString("\n")
}

func writeBaseStage(b *strings.Builder, opts RenderOptions) {
	from := opts.BaseImage
	if opts.Digest != "" {
		from += "@" + opts.Digest
	}
	// The base is deliberately config-free: nothing here changes when the config
	// changes, so neither it nor any stage built FROM it is invalidated by an
	// edit. The full config enters only the config-split stage (below) and the
	// final image.
	b.WriteString("# Shared base: datamitsu binary + writable store dir. Config-free, so config\n")
	b.WriteString("# edits never invalidate it or anything built FROM it.\n")
	fmt.Fprintf(b, "FROM %s AS dm-base\n", from)
	b.WriteString("USER root\n")
	// sliceDir is created here (root, chowned) because the config-split stage
	// writes into it as the non-root user; other stages just inherit it empty.
	// Group 0 + g=u (not the user's own group) keeps the dirs writable for
	// arbitrary-uid runtimes — see the final-stage perms normalization.
	fmt.Fprintf(b, "RUN mkdir -p %s %s %s && chown -R %s:0 %s %s %s && chmod -R g=u %s %s %s\n",
		opts.StoreRoot, opts.WorkDir, sliceDir, opts.User, opts.StoreRoot, opts.WorkDir, sliceDir,
		opts.StoreRoot, opts.WorkDir, sliceDir)
	fmt.Fprintf(b, "USER %s\n", opts.User)
	fmt.Fprintf(b, "ENV DATAMITSU_CACHE_DIR=%s\n", opts.StoreRoot)
	fmt.Fprintf(b, "WORKDIR %s\n\n", opts.WorkDir)
	// Deliberately NO `git init` here. App/runtime stages COPY --link their slice,
	// which recreates the workdir root-owned; a `.git` from this base would then be
	// rejected by git as dubious ownership and hard-fail engine creation. With no
	// `.git` at all, datamitsu proceeds without a git root (the slices are static,
	// so facts are irrelevant). The config-split stage gets its own git init.
}

// builderBase is the parent stage for install stages (rt-*, binary app-*). When
// build args are supplied it is dm-build (which carries them as inherited ENV);
// otherwise install stages derive straight from dm-base and no extra stage exists.
func (o RenderOptions) builderBase() string {
	if len(o.BuildArgs) > 0 {
		return "dm-build"
	}
	return "dm-base"
}

// writeBuildStage emits the dm-build stage: each build arg is declared as an ARG
// (overridable via `docker build --build-arg`) and immediately promoted to an ENV
// so every install stage FROM dm-build inherits it — ARG itself does not cross
// FROM. final stays FROM dm-base, so these never reach the shipped image. Use
// this for build-time knobs like DATAMITSU_INSTALL_TIMEOUT; for secrets prefer
// `RUN --mount=type=secret` over an ARG (which lingers in intermediate layers).
func writeBuildStage(b *strings.Builder, opts RenderOptions) {
	if len(opts.BuildArgs) == 0 {
		return
	}
	b.WriteString("# --- Build env: ARGs promoted to ENV so every install stage inherits them ---\n")
	b.WriteString("FROM dm-base AS dm-build\n")
	keys := make([]string, 0, len(opts.BuildArgs))
	for k := range opts.BuildArgs {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		if v := opts.BuildArgs[k]; v == "" {
			fmt.Fprintf(b, "ARG %s\n", k)
		} else {
			fmt.Fprintf(b, "ARG %s=%s\n", k, strconv.Quote(v))
		}
		fmt.Fprintf(b, "ENV %s=$%s\n", k, k)
	}
	b.WriteString("\n")
}

// writeConfigSplitStage emits the stage that reads the full config once and
// writes a minimal per-stage config slice into sliceDir. Every builder stage
// then COPYs only its own slice, so editing one app changes only that app's
// slice and busts only that app's cache.
func writeConfigSplitStage(b *strings.Builder, opts RenderOptions) {
	b.WriteString("# --- Config split: one minimal config slice per stage (build-cache isolation) ---\n")
	b.WriteString("FROM dm-base AS config-split\n")
	fmt.Fprintf(b, "COPY --chown=%s:%s %s ./\n", opts.User, opts.User, opts.ConfigSource)
	// This stage loads the FULL config, which may read facts() (e.g. isInGitRepo),
	// so it gets a git root. Its workdir is owner-correct (COPY --chown, no
	// COPY --link), so git accepts it — unlike the COPY --link app stages. git init
	// is chained into the same RUN as split-config (one layer; avoids DL3059).
	fmt.Fprintf(b, "RUN git init -q . && datamitsu --config %s devtools split-config --output %s\n\n", opts.configImagePath(), sliceDir)
}

// installCmd is the RUN command a builder stage uses to install one target. The
// stage has no `.git` (the base omits git init), so datamitsu proceeds without a
// git root and the COPY --link root-owned workdir never trips git's ownership check.
func (o RenderOptions) installCmd(args ...string) string {
	parts := append([]string{"datamitsu", "--config", o.configImagePath(), "install"}, args...)
	return "RUN " + strings.Join(parts, " ")
}

// copySlice emits the COPY that brings one stage's config slice in from the
// config-split stage, landing it at the path install reads via --config.
func (o RenderOptions) copySlice(stage string) string {
	src := path.Join(sliceDir, SliceFileName(stage))
	return fmt.Sprintf("COPY --link --from=config-split %s %s", src, o.configImagePath())
}

func writeRuntimeStages(b *strings.Builder, plan Plan, opts RenderOptions) {
	if len(plan.RuntimeStages) == 0 {
		return
	}
	b.WriteString("# --- Runtime stages (one per managed runtime) ---\n")
	for _, rt := range plan.RuntimeStages {
		stage := stageName("rt-", rt.Name)
		fmt.Fprintf(b, "FROM %s AS %s\n", opts.builderBase(), stage)
		fmt.Fprintf(b, "%s\n", opts.copySlice(stage))
		fmt.Fprintf(b, "%s\n\n", opts.installCmd("--runtime", rt.Name))
	}
}

func writeRuntimeAppStages(b *strings.Builder, plan Plan, opts RenderOptions) {
	if len(plan.RuntimeAppStages) == 0 {
		return
	}
	b.WriteString("# --- App stages (runtime-managed; inherit their runtime stage) ---\n")
	for _, ts := range plan.RuntimeAppStages {
		stage := stageName("app-", ts.App)
		fmt.Fprintf(b, "FROM %s AS %s\n", stageName("rt-", ts.Runtime), stage)
		fmt.Fprintf(b, "%s\n", opts.copySlice(stage))
		fmt.Fprintf(b, "%s\n\n", opts.installCmd(opts.appInstallArgs(ts.App)...))
	}
}

func writeBinaryStages(b *strings.Builder, plan Plan, opts RenderOptions) {
	if len(plan.BinaryStages) == 0 {
		return
	}
	b.WriteString("# --- Binary stages (one per downloaded binary) ---\n")
	for _, bs := range plan.BinaryStages {
		stage := stageName("app-", bs.App)
		fmt.Fprintf(b, "FROM %s AS %s\n", opts.builderBase(), stage)
		fmt.Fprintf(b, "%s\n", opts.copySlice(stage))
		fmt.Fprintf(b, "%s\n\n", opts.installCmd(opts.appInstallArgs(bs.App)...))
	}
}

// appInstallArgs is the install argument list for one app. `install` verifies by
// default, so plain `install <app>` runs the version check in-stage; --no-verify
// is appended only when the caller opts out.
func (o RenderOptions) appInstallArgs(app string) []string {
	if o.NoVerify {
		return []string{app, "--no-verify"}
	}
	return []string{app}
}

func writeFinalStage(b *strings.Builder, plan Plan, opts RenderOptions) {
	b.WriteString("# --- Final image: assemble per-app store layers ---\n")
	b.WriteString("FROM dm-base AS final\n")
	// The full config lives in the final image (the base is config-free) so the
	// entrypoint can resolve every app at run time. Its own layer, so a config
	// edit re-pulls only this small layer for end users, not the tool layers.
	fmt.Fprintf(b, "COPY --chown=%s:%s %s ./\n", opts.User, opts.User, opts.ConfigSource)
	writeLabels(b, opts.Labels)
	writeArgs(b, opts.Args)
	writeEnv(b, opts.Env)

	// Runtime store subtrees (skip kinds whose runtime is build-only, e.g. go).
	for _, rt := range plan.RuntimeStages {
		if !runtimeCopiedToFinal(rt.Kind) {
			continue
		}
		writeCopy(b, stageName("rt-", rt.Name), opts.storeAbs(runtimeSubtree(rt.Name)))
	}

	// Per-app store subtrees; uv apps also carry the managed CPython they used.
	for _, ts := range plan.RuntimeAppStages {
		stage := stageName("app-", ts.App)
		writeCopy(b, stage, opts.storeAbs(appEnvSubtree(ts.Kind, ts.App)))
		if ts.Kind == config.RuntimeKindUV {
			writeCopy(b, stage, opts.storeAbs(uvPythonSubtree))
		}
	}

	// Binary store subtrees.
	for _, bs := range plan.BinaryStages {
		writeCopy(b, stageName("app-", bs.App), opts.storeAbs(binaryAppSubtree(bs.App)))
	}

	// Writable store/config dirs for both run-time users. `COPY --link` above
	// recreates the destination's parent dirs (/dm, /dm/store, …) as root:root
	// 0755 in its own layer, shadowing dm-base's datamitsu:0 ones. Restore
	// owner AND group here: chown to the image user + group 0 with group perms
	// mirroring the owner's. That covers the named user (owner) — the default
	// entrypoint path, e.g. GitLab k8s honoring the image USER — AND arbitrary
	// non-root uids whose only predictable membership is group 0 (OpenShift).
	// A chgrp-only normalization left the dirs root-owned, so the named user
	// (primary group != 0) hit "other" perms and `datamitsu init` failed to
	// create /dm/store/.bundles. Directories only: a chmod/chown over file
	// content would copy-up every store file into one duplicate layer and
	// roughly double the image, while creating new files needs only writable
	// directories. The extra trailing layer is metadata-sized and sits after
	// the per-subtree COPY block, which the oci-map postprocess locates by
	// probing, not position.
	b.WriteString("USER root\n")
	fmt.Fprintf(b, "RUN find %s %s -type d -exec chown %s:0 {} + -exec chmod g=u {} +\n", opts.StoreRoot, opts.WorkDir, opts.User)
	fmt.Fprintf(b, "USER %s\n", opts.User)
	b.WriteString("WORKDIR /workspace\n")

	entrypoint := opts.Entrypoint
	if entrypoint == nil {
		entrypoint = []string{"/usr/local/bin/datamitsu", "--before-config", opts.configImagePath()}
	}
	fmt.Fprintf(b, "ENTRYPOINT %s\n", jsonArray(entrypoint))
	if len(opts.Cmd) > 0 {
		fmt.Fprintf(b, "CMD %s\n", jsonArray(opts.Cmd))
	}
}

func writeLabels(b *strings.Builder, labels map[string]string) {
	if len(labels) == 0 {
		return
	}
	keys := make([]string, 0, len(labels))
	for k := range labels {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(b, "LABEL %s=%s\n", k, strconv.Quote(labels[k]))
	}
}

func writeArgs(b *strings.Builder, args map[string]string) {
	if len(args) == 0 {
		return
	}
	keys := make([]string, 0, len(args))
	for k := range args {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		// Empty value = bare `ARG NAME` (default comes from --build-arg at build time).
		if args[k] == "" {
			fmt.Fprintf(b, "ARG %s\n", k)
			continue
		}
		fmt.Fprintf(b, "ARG %s=%s\n", k, strconv.Quote(args[k]))
	}
}

func writeEnv(b *strings.Builder, vars map[string]string) {
	if len(vars) == 0 {
		return
	}
	keys := make([]string, 0, len(vars))
	for k := range vars {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(b, "ENV %s=%s\n", k, strconv.Quote(vars[k]))
	}
}

func writeCopy(b *strings.Builder, fromStage, abs string) {
	fmt.Fprintf(b, "COPY --link --from=%s %s %s\n", fromStage, abs, abs)
}

// jsonArray renders a string slice as a JSON array for exec-form instructions.
// strconv.Quote yields JSON-compatible quoting for the ASCII paths/flags used in
// entrypoints, avoiding an encoding/json dependency for this hot, simple path.
func jsonArray(items []string) string {
	quoted := make([]string, len(items))
	for i, s := range items {
		quoted[i] = strconv.Quote(s)
	}
	return "[" + strings.Join(quoted, ",") + "]"
}

// stageName builds a Docker-safe stage name (lowercase, [a-z0-9_.-]) from a
// prefix and a raw app/runtime name.
func stageName(prefix, raw string) string {
	var b strings.Builder
	b.WriteString(prefix)
	for _, r := range strings.ToLower(raw) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '_', r == '.', r == '-':
			b.WriteRune(r)
		default:
			b.WriteRune('-')
		}
	}
	return b.String()
}
