package dockerfile

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/datamitsu/datamitsu/internal/binmanager"
	"github.com/datamitsu/datamitsu/internal/config"
)

// sliceDir is the in-image directory the config-split stage writes per-stage
// config slices into, and that every builder stage COPYs its own slice from.
// The generator (COPY lines) and `devtools split-config` (file names) must agree
// on it, so it is the single source of truth for both.
const sliceDir = "/slices"

// Slice is one stage's minimal config: just the app (and its runtime) that stage
// installs, nothing else. Each stage loads only its slice, so editing one app
// changes only that app's slice — and therefore busts only that app's build
// cache, not the whole image.
type Slice struct {
	StageName string         // e.g. "rt-node", "app-prettier"
	FileName  string         // SliceFileName(StageName)
	Config    *config.Config // minimal config containing only this stage's target
}

// SliceFileName is the slice file name for a stage. Shared by the generator's
// COPY lines and split-config's output so they always line up.
func SliceFileName(stage string) string { return stage + ".js" }

// BuildSlices returns one minimal config slice per stage in the plan: a runtime
// stage gets only its runtime; a binary stage only its binary; a runtime-managed
// app gets its app plus the runtime it installs under (so install can resolve the
// runtime reference); a parser stage gets only its `parsers` entry. Order mirrors
// the plan for deterministic output.
func BuildSlices(plan Plan, apps binmanager.MapOfApps, runtimes config.MapOfRuntimes, parsers config.MapOfParsers) []Slice {
	slices := make([]Slice, 0, len(plan.RuntimeStages)+len(plan.RuntimeAppStages)+len(plan.BinaryStages)+len(plan.ParserStages))

	for _, rt := range plan.RuntimeStages {
		stage := stageName("rt-", rt.Name)
		slices = append(slices, Slice{
			StageName: stage,
			FileName:  SliceFileName(stage),
			Config:    &config.Config{Runtimes: config.MapOfRuntimes{rt.Name: runtimes[rt.Name]}},
		})
	}

	for _, ts := range plan.RuntimeAppStages {
		stage := stageName("app-", ts.App)
		slices = append(slices, Slice{
			StageName: stage,
			FileName:  SliceFileName(stage),
			Config: &config.Config{
				Apps:     binmanager.MapOfApps{ts.App: apps[ts.App]},
				Runtimes: config.MapOfRuntimes{ts.Runtime: runtimes[ts.Runtime]},
			},
		})
	}

	for _, bs := range plan.BinaryStages {
		stage := stageName("app-", bs.App)
		slices = append(slices, Slice{
			StageName: stage,
			FileName:  SliceFileName(stage),
			Config:    &config.Config{Apps: binmanager.MapOfApps{bs.App: apps[bs.App]}},
		})
	}

	for _, ps := range plan.ParserStages {
		stage := stageName("parser-", ps.Module)
		slices = append(slices, Slice{
			StageName: stage,
			FileName:  SliceFileName(stage),
			Config:    &config.Config{Parsers: config.MapOfParsers{ps.Module: parsers[ps.Module]}},
		})
	}

	return slices
}

// RenderSlice serializes a minimal config into a self-contained JS config module
// that `datamitsu install --config` can load. getMinVersion returns "0.0.0" so a
// slice never trips the wrapper's version gate, and getConfig ignores its input
// and returns exactly this stage's app/runtime.
//
// The output is a projection of the Go struct, not a round-trip of the author's
// config: json.Marshal writes the fields this binary knows about, with this
// binary's defaults applied. That is fine for the app/runtime slices it is built
// for — install needs no tool definitions — but it means a slice must never be
// used to carry tools. A tool-bearing config passed through here would be
// re-emitted under the current schema, silently dropping any field the running
// binary does not have and freezing inferred values as if the author had
// written them. Keep slices app/runtime-only.
func RenderSlice(cfg *config.Config) (string, error) {
	data, err := json.Marshal(cfg)
	if err != nil {
		return "", fmt.Errorf("marshal slice config: %w", err)
	}

	var b strings.Builder
	b.WriteString("// GENERATED by `datamitsu devtools split-config` — minimal per-stage config. DO NOT EDIT.\n")
	b.WriteString("function getMinVersion() { return \"0.0.0\"; }\n")
	b.WriteString("function getConfig() { return ")
	b.Write(data)
	b.WriteString("; }\n")
	// Assign to globalThis so the loader finds the exports even if StripTypes ever
	// compiles this into a module scope (where top-level decls are not global).
	b.WriteString("globalThis.getMinVersion = getMinVersion;\n")
	b.WriteString("globalThis.getConfig = getConfig;\n")
	return b.String(), nil
}
