package cmd

import (
	"strings"
	"testing"

	"github.com/datamitsu/datamitsu/internal/llmsdocs"

	"github.com/spf13/cobra"
)

// cliCommandsPage is the reference page that documents the command surface.
const cliCommandsPage = "reference/cli-commands"

// cobraBuiltinCommands are generated by cobra rather than written by us, so the
// reference page is not expected to document them.
var cobraBuiltinCommands = map[string]bool{
	"help":       true,
	"completion": true,
}

// TestCLICommandsPageCoversLeaves is the one place the "embedded docs match this
// binary" promise can be checked mechanically. The docs are hand-written prose,
// so their content cannot be derived from the code — but a command that exists
// and is documented nowhere is unambiguous drift, and it is exactly what an
// agent reading `datamitsu llms reference/cli-commands` would fail to discover.
//
// It runs in the default `go test ./...` and needs no website toolchain,
// because it reads the committed snapshot rather than the site build.
func TestCLICommandsPageCoversLeaves(t *testing.T) {
	docs, err := llmsdocs.Load()
	if err != nil {
		t.Fatalf("llmsdocs.Load() error = %v", err)
	}
	page, err := docs.Page(cliCommandsPage)
	if err != nil {
		t.Fatalf("Page(%q) error = %v", cliCommandsPage, err)
	}

	for _, leaf := range leafCommandNames(rootCmd) {
		if !strings.Contains(page.Body, leaf) {
			t.Errorf("command %q is not mentioned in the embedded %s page; document it in "+
				"website/docs/reference/cli-commands.md and re-run `task gen:llms-docs`", leaf, cliCommandsPage)
		}
	}
}

// TestLlmsPageIsResolvable guards the help text: every page named in the
// command's own examples must actually resolve, so a user copying a line out of
// `datamitsu llms --help` never hits an unknown-page error.
func TestLlmsPageIsResolvable(t *testing.T) {
	docs, err := llmsdocs.Load()
	if err != nil {
		t.Fatalf("llmsdocs.Load() error = %v", err)
	}

	for _, arg := range []string{"about", "contributing/brand-guidelines", "brand-guidelines"} {
		if !strings.Contains(llmsCmd.Long, arg) {
			t.Errorf("help text no longer mentions %q; keep this list in sync with the examples", arg)
		}
		if _, err := docs.Resolve(arg); err != nil {
			t.Errorf("help text example %q does not resolve: %v", arg, err)
		}
	}
}

// leafCommandNames returns the name of every command that has no subcommands of
// its own, which is the set a user can actually invoke.
func leafCommandNames(root *cobra.Command) []string {
	var names []string
	var walk func(c *cobra.Command)
	walk = func(c *cobra.Command) {
		subs := c.Commands()
		if len(subs) == 0 {
			names = append(names, c.Name())
			return
		}
		for _, sub := range subs {
			if cobraBuiltinCommands[sub.Name()] {
				continue
			}
			walk(sub)
		}
	}

	for _, sub := range root.Commands() {
		if cobraBuiltinCommands[sub.Name()] {
			continue
		}
		walk(sub)
	}
	return names
}
