package cmd

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/datamitsu/datamitsu/internal/binmanager"
	"github.com/datamitsu/datamitsu/internal/config"
	enginetools "github.com/datamitsu/datamitsu/internal/engine/tools"
	"github.com/datamitsu/datamitsu/internal/install"
	"github.com/datamitsu/datamitsu/internal/project"
	"github.com/datamitsu/datamitsu/internal/runner"
	"github.com/datamitsu/datamitsu/internal/tooling"
	"github.com/datamitsu/datamitsu/internal/traverser"

	"github.com/spf13/cobra"
)

var (
	setupDryRun        bool
	setupSkipFix       bool
	setupOptInTools    bool
	setupSelectedTools string
)

// optInIgnoreFilename is the name of the ignore file generated by
// `datamitsu setup --opt-in-tools`, written at the git root.
const optInIgnoreFilename = ".datamitsuignore"

var setupCmd = &cobra.Command{
	Use:   "setup",
	Short: "Setup configuration files",
	Long: `Sets up configuration files for detected project types.
This command aggressively replaces existing configs by deleting all known variants
and creating new ones based on the configuration.`,
	RunE: runSetup,
}

func init() {
	setupCmd.Flags().BoolVar(&setupDryRun, "dry-run", false, "Show what would be done without making changes")
	setupCmd.Flags().BoolVar(&setupSkipFix, "skip-fix", false, "Skip running fix after setup")
	setupCmd.Flags().BoolVar(&setupOptInTools, "opt-in-tools", false, "Also generate an all-disabled .datamitsuignore so tools are opt-in (enable them by removing names from the list)")
	setupCmd.Flags().StringVar(&setupSelectedTools, "tools", "", "Comma-separated list of tools to scope setup to (only their config files are written)")
	rootCmd.AddCommand(setupCmd)
}

func runSetup(cmd *cobra.Command, args []string) error {
	ctx := context.Background()

	// Get cwd
	cwdPath, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("failed to get cwd: %w", err)
	}

	// Get root path
	rootPath, err := traverser.GetGitRoot(ctx, cwdPath)
	if err != nil {
		return fmt.Errorf("failed to get git root: %w", err)
	}

	// When generating an opt-in ignore file, fail fast before any installs if a
	// .datamitsuignore already exists so manual tool selections are never lost.
	if setupOptInTools {
		if err := ensureNoExistingIgnore(rootPath); err != nil {
			return err
		}
	}

	// Load configuration
	cfg, layerMap, vm, err := loadConfig()
	if err != nil {
		return fmt.Errorf("failed to load config: %w", err)
	}

	// Parse and validate --tools: scopes which config files setup writes.
	selectedTools := parseSelectedTools(setupSelectedTools)
	if err := validateSelectedTools(selectedTools, cfg.Tools); err != nil {
		return err
	}

	registry := buildConfigLinksRegistry(cfg.Apps, cfg.Bundles)
	if err := enginetools.RegisterConfigLinksInVM(vm, registry, rootPath); err != nil {
		return fmt.Errorf("failed to register config links in VM: %w", err)
	}

	// Detect project types and locations
	detector := project.NewDetector(rootPath, cfg.ProjectTypes)
	locations, err := detector.DetectAllWithLocations(ctx)
	if err != nil {
		return fmt.Errorf("failed to detect project types: %w", err)
	}

	// Group locations by path to get all types for each location
	locationMap := make(map[string][]string)
	for _, loc := range locations {
		locationMap[loc.Path] = append(locationMap[loc.Path], loc.Type)
	}

	detectedCount := len(locationMap)

	// Ensure rootPath is always in the map so git-root scoped configs can run
	if _, ok := locationMap[rootPath]; !ok {
		locationMap[rootPath] = []string{}
	}

	// Sort paths for deterministic output
	sortedPaths := make([]string, 0, len(locationMap))
	for path := range locationMap {
		sortedPaths = append(sortedPaths, path)
	}
	sort.Strings(sortedPaths)

	if detectedCount == 0 {
		fmt.Println("⚠️  No project types detected")
	} else {
		fmt.Printf("📦 Found %d project location(s)\n", detectedCount)
		for _, path := range sortedPaths {
			types := locationMap[path]
			if len(types) == 0 {
				continue
			}
			relPath, _ := filepath.Rel(rootPath, path)
			if relPath == "" || relPath == "." {
				relPath = "."
			}
			fmt.Printf("   %s: %v\n", relPath, types)
		}
	}
	fmt.Println()

	var allResults []install.InstallResult
	for _, projectPath := range sortedPaths {
		projectTypes := locationMap[projectPath]
		// Create installer for this specific location
		installer := install.NewInstaller(rootPath, projectPath, projectTypes, selectedTools, cfg.Init, vm, layerMap)

		// Install configs
		results, err := installer.InstallAll(ctx, setupDryRun)
		if err != nil {
			return fmt.Errorf("failed to install configs in %s: %w", projectPath, err)
		}

		allResults = append(allResults, results...)
	}

	results := deduplicateGitRootResults(allResults)

	// Print results
	if setupDryRun {
		fmt.Println("🔍 DRY-RUN MODE - No changes will be made")
		fmt.Println()
	}

	var installErrors []error
	for _, result := range results {
		if result.Action == "skipped" {
			continue
		}

		relPath, _ := filepath.Rel(rootPath, result.FilePath)

		switch result.Action {
		case "created":
			fmt.Printf("✨ Created: %s\n", relPath)
		case "patched":
			fmt.Printf("🔧 Patched: %s\n", relPath)
		case "replaced":
			fmt.Printf("🔄 Replaced: %s\n", relPath)
		case "linked":
			if result.LinkTarget != "" {
				linkTargetRel, _ := filepath.Rel(rootPath, filepath.Join(filepath.Dir(result.FilePath), result.LinkTarget))
				fmt.Printf("🔗 Linked: %s -> %s\n", relPath, linkTargetRel)
			} else {
				fmt.Printf("🔗 Linked: %s\n", relPath)
			}
		case "deleted":
			fmt.Printf("🗑️  Deleted configuration files\n")
		}

		// Only show deleted files if they're different from the created/patched file
		if len(result.DeletedFiles) > 0 {
			for _, deleted := range result.DeletedFiles {
				// Skip showing deletion if it's the same file being created/patched
				if deleted == result.FilePath {
					continue
				}
				relDeleted, _ := filepath.Rel(rootPath, deleted)
				fmt.Printf("   ❌ Deleted: %s\n", relDeleted)
			}
		}

		if result.Error != nil {
			fmt.Printf("   ⚠️  Error: %v\n", result.Error)
			installErrors = append(installErrors, fmt.Errorf("%s: %w", result.ConfigName, result.Error))
		}
	}

	if len(installErrors) > 0 {
		return fmt.Errorf("setup completed with %d error(s)", len(installErrors))
	}

	// Under --tools, surface any selected tool for which setup generated nothing
	// so the user knows it was a no-op. This is not an error: a tool may have no
	// config at all, or its only config may not apply to this project.
	reportToolsWithoutGeneratedConfig(selectedTools, cfg.Init, results)

	// Generate the all-disabled opt-in ignore file before the post-setup fix so
	// that fix already respects the opt-in state (it becomes a no-op when every
	// tool is disabled).
	if setupOptInTools {
		if err := writeOptInIgnore(rootPath, cfg.Tools, setupDryRun); err != nil {
			return err
		}
	}

	if !setupDryRun {
		fmt.Println()
		fmt.Println("✅ Setup complete")

		// Run fix operation after setup unless skipped
		if !setupSkipFix {
			fmt.Println()
			fmt.Println("🔧 Running fix operation...")
			fmt.Println()

			if err := runner.Run(config.OpFix, []string{}, "", false, setupSelectedTools, func() (*config.Config, string, error) {
				cfg, _, _, err := loadConfig()
				return cfg, "", err
			}); err != nil {
				return fmt.Errorf("fix operation failed: %w", err)
			}
		}
	}

	return nil
}

// parseSelectedTools splits a comma-separated --tools value into a deduplicated,
// trimmed list of tool names. An empty input yields nil (no filter), mirroring
// how fix/lint parse the same flag.
func parseSelectedTools(flagValue string) []string {
	if flagValue == "" {
		return nil
	}
	var selected []string
	seen := make(map[string]bool)
	for t := range strings.SplitSeq(flagValue, ",") {
		t = strings.TrimSpace(t)
		if t != "" && !seen[t] {
			seen[t] = true
			selected = append(selected, t)
		}
	}
	return selected
}

// validateSelectedTools verifies every name in selected is a configured tool,
// returning a *tooling.ToolNotFoundError (the same error fix/lint produce) that
// lists the unknown names and the available set. Returns nil when selected is
// empty or all names are known.
func validateSelectedTools(selected []string, tools config.MapOfTools) error {
	if len(selected) == 0 {
		return nil
	}
	var notFound []string
	for _, name := range selected {
		if _, ok := tools[name]; !ok {
			notFound = append(notFound, name)
		}
	}
	if len(notFound) == 0 {
		return nil
	}
	available := make([]string, 0, len(tools))
	for name := range tools {
		available = append(available, name)
	}
	sort.Strings(available)
	return &tooling.ToolNotFoundError{NotFound: notFound, Available: available}
}

// toolsWithoutGeneratedConfig returns the sorted subset of selected tools for
// which setup produced no config file — either because no config is associated
// with the tool, or because every associated config was skipped (e.g. its
// projectTypes did not match this location). It is derived from the actual
// install results so project-type skips are surfaced too, not just missing
// associations. Returns nil when no tools were selected.
func toolsWithoutGeneratedConfig(selected []string, configs config.MapOfConfigInit, results []install.InstallResult) []string {
	if len(selected) == 0 {
		return nil
	}
	generated := make(map[string]bool)
	for _, r := range results {
		if r.Action == "" || r.Action == "skipped" {
			continue
		}
		ci, ok := configs[r.ConfigName]
		if !ok {
			continue
		}
		for _, t := range ci.Tools {
			generated[t] = true
		}
	}
	var none []string
	for _, t := range selected {
		if !generated[t] {
			none = append(none, t)
		}
	}
	sort.Strings(none)
	return none
}

// reportToolsWithoutGeneratedConfig prints an info line for each selected tool
// that setup generated no config for. This keeps tool-scoped setup non-fatal
// while still surfacing the no-op (a tool may own no config, or its only config
// may not apply to this project).
func reportToolsWithoutGeneratedConfig(selected []string, configs config.MapOfConfigInit, results []install.InstallResult) {
	for _, t := range toolsWithoutGeneratedConfig(selected, configs, results) {
		fmt.Printf("ℹ️  No config files were generated for tool %q\n", t)
	}
}

// deduplicateGitRootResults removes duplicate results for git-root scoped configs.
// When multiple project locations produce results for the same FilePath and all
// have Scope="git-root", only one result is kept. If any result in the group has an
// error, the first error result is preferred so errors are never silently dropped.
func deduplicateGitRootResults(results []install.InstallResult) []install.InstallResult {
	type group struct {
		indices    []int
		allGitRoot bool
	}

	groups := make(map[string]*group)
	var order []string

	for i, r := range results {
		g, exists := groups[r.FilePath]
		if !exists {
			g = &group{allGitRoot: true}
			groups[r.FilePath] = g
			order = append(order, r.FilePath)
		}
		g.indices = append(g.indices, i)
		if r.Scope != config.ScopeGitRoot {
			g.allGitRoot = false
		}
	}

	keep := make(map[int]bool)
	for _, path := range order {
		g := groups[path]
		if g.allGitRoot && len(g.indices) > 1 {
			bestIdx := g.indices[0]
			for _, idx := range g.indices {
				if results[idx].Error != nil {
					bestIdx = idx
					break
				}
			}
			keep[bestIdx] = true
		} else {
			for _, idx := range g.indices {
				keep[idx] = true
			}
		}
	}

	var deduped []install.InstallResult
	for i, r := range results {
		if keep[i] {
			deduped = append(deduped, r)
		}
	}

	return deduped
}

// buildOptInIgnoreContent generates canonical .datamitsuignore content that
// disables every configured tool via a single catch-all rule (the opt-in
// model). Tool names are sorted for deterministic, lint-stable output. It
// returns the generated content and the number of tools listed. When there are
// no tools, it returns an empty string and a count of 0.
func buildOptInIgnoreContent(tools config.MapOfTools) (string, int) {
	if len(tools) == 0 {
		return "", 0
	}

	names := make([]string, 0, len(tools))
	for name := range tools {
		names = append(names, name)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("# Generated by `datamitsu setup --opt-in-tools`.\n")
	b.WriteString("# All configured tools are disabled by default (opt-in model).\n")
	b.WriteString("# Enable a tool by removing it from the list below (or add \"!**/*: <tool>\").\n")
	b.WriteString("**/*: ")
	b.WriteString(strings.Join(names, ", "))
	b.WriteString("\n")

	return b.String(), len(names)
}

// ensureNoExistingIgnore guards against clobbering a manually maintained
// .datamitsuignore. It returns an error if the file already exists at rootPath
// (so opt-in tool selections are never silently lost), nil when it is absent,
// and surfaces any other stat error.
func ensureNoExistingIgnore(rootPath string) error {
	path := filepath.Join(rootPath, optInIgnoreFilename)
	_, err := os.Stat(path)
	if err == nil {
		return fmt.Errorf("%s already exists at %s; refusing to overwrite (remove it first to regenerate)", optInIgnoreFilename, rootPath)
	}
	if os.IsNotExist(err) {
		return nil
	}
	return fmt.Errorf("failed to stat %s: %w", path, err)
}

// writeOptInIgnore generates an all-disabled .datamitsuignore at rootPath listing
// every configured tool (the opt-in model). With no tools it writes nothing and
// prints an info line. In dry-run mode it reports intent without touching the
// filesystem; in real mode it writes the file with 0o644 permissions.
func writeOptInIgnore(rootPath string, tools config.MapOfTools, dryRun bool) error {
	content, count := buildOptInIgnoreContent(tools)
	if count == 0 {
		fmt.Println("ℹ️  No configured tools to disable; skipping .datamitsuignore generation")
		return nil
	}

	path := filepath.Join(rootPath, optInIgnoreFilename)

	if dryRun {
		fmt.Printf("🔍 Would create: %s (%d tool(s) disabled)\n", optInIgnoreFilename, count)
		return nil
	}

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("failed to write %s: %w", path, err)
	}
	fmt.Printf("✨ Created: %s (%d tool(s) disabled)\n", optInIgnoreFilename, count)
	return nil
}

func buildConfigLinksRegistry(apps binmanager.MapOfApps, bundles binmanager.MapOfBundles) map[string]string {
	registry := make(map[string]string)
	for appName, app := range apps {
		for linkName := range app.Links {
			registry[linkName] = appName
		}
	}
	for bundleName, bundle := range bundles {
		if bundle == nil {
			continue
		}
		for linkName := range bundle.Links {
			registry[linkName] = bundleName
		}
	}
	return registry
}
