package cmd

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/datamitsu/datamitsu/internal/binmanager"
	clr "github.com/datamitsu/datamitsu/internal/color"
	"github.com/datamitsu/datamitsu/internal/config"
	enginetools "github.com/datamitsu/datamitsu/internal/engine/tools"
	"github.com/datamitsu/datamitsu/internal/install"
	"github.com/datamitsu/datamitsu/internal/ldflags"
	"github.com/datamitsu/datamitsu/internal/project"
	"github.com/datamitsu/datamitsu/internal/runner"
	"github.com/datamitsu/datamitsu/internal/term"
	"github.com/datamitsu/datamitsu/internal/tooling"
	"github.com/datamitsu/datamitsu/internal/traverser"
	"github.com/datamitsu/datamitsu/internal/ui"

	"github.com/spf13/cobra"
)

var (
	setupDryRun        bool
	setupSkipFix       bool
	setupOptInTools    bool
	setupSelectedTools string
	setupNoVerifyHash  bool
)

// optInIgnoreFilename is the name of the ignore file generated by
// `datamitsu setup --opt-in-tools`, written at the git root.
const optInIgnoreFilename = ".datamitsuignore"

var setupCmd = &cobra.Command{
	Use:   "setup",
	Short: "Setup configuration files",
	Long: `Sets up configuration files for detected project types.
This command aggressively replaces existing configs by deleting all known variants
and creating new ones based on the configuration.`,
	RunE: runSetup,
}

func init() {
	setupCmd.Flags().BoolVar(&setupDryRun, "dry-run", false, "Show what would be done without making changes")
	setupCmd.Flags().BoolVar(&setupSkipFix, "skip-fix", false, "Skip running fix after setup")
	setupCmd.Flags().BoolVar(&setupOptInTools, "opt-in-tools", false, "Also generate an all-disabled .datamitsuignore so tools are opt-in (enable them by removing names from the list)")
	setupCmd.Flags().StringVar(&setupSelectedTools, "tools", "", "Comma-separated list of tools to scope setup to (only their config files are written)")
	setupCmd.Flags().BoolVar(&setupNoVerifyHash, "no-verify-hash", false, "Skip expectChainHash verification (write even when a pinned config drifted from its upstream chain)")
	rootCmd.AddCommand(setupCmd)
}

func runSetup(_ *cobra.Command, _ []string) error {
	ctx := context.Background()
	start := time.Now()

	cwdPath, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("failed to get cwd: %w", err)
	}

	rootPath, err := traverser.GetGitRoot(ctx, cwdPath)
	if err != nil {
		return fmt.Errorf("failed to get git root: %w", err)
	}

	// When generating an opt-in ignore file, fail fast before any installs if a
	// .datamitsuignore already exists so manual tool selections are never lost.
	if setupOptInTools {
		if err := ensureNoExistingIgnore(rootPath); err != nil {
			return err
		}
	}

	cfg, layerMap, vm, err := loadConfig()
	if err != nil {
		return fmt.Errorf("failed to load config: %w", err)
	}

	// Gate before any filesystem writes: a pinned config whose upstream chain
	// drifted halts the whole run with a report, so overrides are never silently
	// overwritten. Runs in dry-run too. Printed before the display is activated.
	if err := verifyChainHashes(layerMap, setupNoVerifyHash); err != nil {
		return err
	}

	// Parse and validate --tools: scopes which config files setup writes.
	selectedTools := parseSelectedTools(setupSelectedTools)
	if err := validateSelectedTools(selectedTools, cfg.Tools); err != nil {
		return err
	}

	registry := buildConfigLinksRegistry(cfg.Apps, cfg.Bundles)
	if err := enginetools.RegisterConfigLinksInVM(vm, registry, rootPath); err != nil {
		return fmt.Errorf("failed to register config links in VM: %w", err)
	}

	// Detect project types and locations
	detector := project.NewDetector(rootPath, cfg.ProjectTypes)
	locations, err := detector.DetectAllWithLocations(ctx)
	if err != nil {
		return fmt.Errorf("failed to detect project types: %w", err)
	}

	// Group locations by path to get all types for each location
	locationMap := make(map[string][]string)
	for _, loc := range locations {
		locationMap[loc.Path] = append(locationMap[loc.Path], loc.Type)
	}
	detectedCount := len(locationMap)

	// Ensure rootPath is always in the map so git-root scoped configs can run
	if _, ok := locationMap[rootPath]; !ok {
		locationMap[rootPath] = []string{}
	}

	// Sort paths for deterministic output
	sortedPaths := make([]string, 0, len(locationMap))
	for path := range locationMap {
		sortedPaths = append(sortedPaths, path)
	}
	sort.Strings(sortedPaths)

	// Activate the shared display and frame the whole run as one "setup" bracket.
	disp := ui.New(term.DetectMode())
	restore := ui.Activate(disp)
	closed := false
	closeSetup := func() {
		if closed {
			return
		}
		closed = true
		disp.Close()
		restore()
	}
	defer closeSetup()

	disp.Banner(ldflags.PackageName, ldflags.Version)

	disp.PhaseOpen("setup")
	if detectedCount == 0 {
		disp.PhaseBody(clr.Yellow("no project types detected"))
	} else {
		disp.PhaseBody(fmt.Sprintf("%d %s", detectedCount, pluralWord(detectedCount, "location", "locations")))
		seen := make(map[string]bool)
		var unionTypes []string
		for _, path := range sortedPaths {
			for _, t := range locationMap[path] {
				st := shortInitType(t)
				if !seen[st] {
					seen[st] = true
					unionTypes = append(unionTypes, st)
				}
			}
		}
		if len(unionTypes) > 0 {
			disp.PhaseBody(clr.Faint(strings.Join(unionTypes, " · ")))
		}
	}
	if setupDryRun {
		disp.PhaseBody("")
		disp.PhaseBody(clr.Cyan("dry-run") + clr.Faint(" — no changes will be made"))
	}

	var allResults []install.InstallResult
	for _, projectPath := range sortedPaths {
		projectTypes := locationMap[projectPath]
		installer := install.NewInstaller(rootPath, projectPath, projectTypes, selectedTools, cfg.Setup, vm, layerMap)
		results, err := installer.InstallAll(ctx, setupDryRun)
		if err != nil {
			return fmt.Errorf("failed to install configs in %s: %w", projectPath, err)
		}
		allResults = append(allResults, results...)
	}
	results := deduplicateGitRootResults(allResults)

	// Group results by action for a compact, scannable render. Notable changes
	// (created/replaced/linked/removed/errors) are always listed; the bulk of
	// routine patches is collapsed to a count outside dry-run, where the full
	// list is itself the preview.
	var created, replaced, linked, patched, removed, failedRows []setupRow
	var installErrors []error
	fileCount := 0
	for _, result := range results {
		if result.Action == "skipped" || result.Action == "" {
			continue
		}
		relPath, _ := filepath.Rel(rootPath, result.FilePath)
		switch result.Action {
		case "created":
			created = append(created, setupRow{clr.Green("+"), relPath})
			fileCount++
		case "patched":
			patched = append(patched, setupRow{clr.Faint("~"), relPath})
			fileCount++
		case "replaced":
			replaced = append(replaced, setupRow{clr.Yellow("±"), relPath})
			fileCount++
		case "linked":
			text := relPath
			if result.LinkTarget != "" {
				linkTargetRel, _ := filepath.Rel(rootPath, filepath.Join(filepath.Dir(result.FilePath), result.LinkTarget))
				text = relPath + clr.Faint(" → "+linkTargetRel)
			}
			linked = append(linked, setupRow{clr.Cyan("↳"), text})
			fileCount++
		}
		for _, deleted := range result.DeletedFiles {
			if deleted == result.FilePath {
				continue
			}
			relDeleted, _ := filepath.Rel(rootPath, deleted)
			removed = append(removed, setupRow{clr.Red("−"), relDeleted})
		}
		if result.Error != nil {
			failedRows = append(failedRows, setupRow{clr.Red("✗"), relPath + clr.Faint(": "+result.Error.Error())})
			installErrors = append(installErrors, fmt.Errorf("%s: %w", result.ConfigName, result.Error))
		}
	}

	setupSection(disp, "created", created)
	setupSection(disp, "replaced", replaced)
	setupSection(disp, "linked", linked)
	setupSection(disp, "removed", removed)
	if setupDryRun {
		setupSection(disp, "patched", patched)
	} else if len(patched) > 0 {
		disp.PhaseBody("")
		disp.PhaseBody(clr.Bold("patched") + clr.Faint(fmt.Sprintf("  %d files", len(patched))))
	}
	setupSection(disp, "errors", failedRows)

	// Surface tool-scoped no-ops (a tool may own no config, or its only config
	// may not apply here). Informational, not an error.
	for _, t := range toolsWithoutGeneratedConfig(selectedTools, cfg.Setup, results) {
		disp.PhaseBody(clr.Faint("no config generated for " + t))
	}

	// Generate the all-disabled opt-in ignore file before the post-setup fix so
	// that fix already respects the opt-in state.
	if len(installErrors) == 0 && setupOptInTools {
		if err := writeOptInIgnore(rootPath, cfg.Tools, setupDryRun); err != nil {
			return err
		}
	}

	printSetupFooter(disp, setupFooterCounts{
		files:    fileCount,
		created:  len(created),
		replaced: len(replaced),
		linked:   len(linked),
		patched:  len(patched),
		removed:  len(removed),
		failed:   len(installErrors),
		dur:      ui.FormatDurationShort(time.Since(start).Milliseconds()),
		dryRun:   setupDryRun,
	})

	if len(installErrors) > 0 {
		return fmt.Errorf("setup completed with %d error(s)", len(installErrors))
	}

	// Tear down the setup frame before the post-setup fix renders its own frame
	// (it reuses the banner already shown above).
	closeSetup()

	if !setupDryRun && !setupSkipFix {
		if err := runner.RunContinuation(config.OpFix, []string{}, "", false, setupSelectedTools, func() (*config.Config, string, error) {
			cfg, _, _, err := loadConfig()
			return cfg, "", err
		}); err != nil {
			return fmt.Errorf("fix operation failed: %w", err)
		}
	}

	return nil
}

// setupRow is one item line in a setup action group.
type setupRow struct {
	sym  string // colored glyph
	text string
}

// setupSection renders one "┃ <title>" group with "┃   <sym> <text>" item rows.
// Nothing is printed for an empty group.
func setupSection(disp *ui.Display, title string, rows []setupRow) {
	if len(rows) == 0 {
		return
	}
	disp.PhaseBody("")
	disp.PhaseBody(clr.Bold(title))
	for _, r := range rows {
		disp.PhaseBody("  " + r.sym + " " + r.text)
	}
}

// pluralWord picks the singular or plural form based on n.
func pluralWord(n int, singular, plural string) string {
	if n == 1 {
		return singular
	}
	return plural
}

// setupFooterCounts carries the tallies shown in the closing bracket rule.
type setupFooterCounts struct {
	files, created, replaced, linked, patched, removed, failed int
	dur                                                        string
	dryRun                                                     bool
}

// printSetupFooter renders the closing "┗━ … ━" rule summarizing the run.
func printSetupFooter(disp *ui.Display, c setupFooterCounts) {
	add := func(parts []string, n int, label string) []string {
		if n <= 0 {
			return parts
		}
		return append(parts, fmt.Sprintf("%d %s", n, label))
	}

	var parts []string
	parts = add(parts, c.files, "files")
	parts = add(parts, c.created, "created")
	parts = add(parts, c.replaced, "replaced")
	parts = add(parts, c.linked, "linked")
	parts = add(parts, c.patched, "patched")
	parts = add(parts, c.removed, "removed")
	parts = append(parts, c.dur)
	body := strings.Join(parts, " · ")

	prefix := "ready"
	switch {
	case c.failed > 0:
		prefix = "failed"
	case c.dryRun:
		prefix = "dry-run"
	}

	plain := prefix + " · " + body
	coloredPrefix := clr.Bold(prefix)
	if c.failed > 0 {
		coloredPrefix = clr.Bold(clr.Red(prefix))
	}
	colored := coloredPrefix + clr.Faint(" · "+body)
	if c.failed > 0 {
		fp := fmt.Sprintf("%d failed", c.failed)
		plain += " · " + fp
		colored += clr.Faint(" · ") + clr.Red(fp)
	}

	disp.PhaseClose(plain, colored)
}

// parseSelectedTools splits a comma-separated --tools value into a deduplicated,
// trimmed list of tool names. An empty input yields nil (no filter), mirroring
// how fix/lint parse the same flag.
func parseSelectedTools(flagValue string) []string {
	if flagValue == "" {
		return nil
	}
	var selected []string
	seen := make(map[string]bool)
	for t := range strings.SplitSeq(flagValue, ",") {
		t = strings.TrimSpace(t)
		if t != "" && !seen[t] {
			seen[t] = true
			selected = append(selected, t)
		}
	}
	return selected
}

// validateSelectedTools verifies every name in selected is a configured tool,
// returning a *tooling.ToolNotFoundError (the same error fix/lint produce) that
// lists the unknown names and the available set. Returns nil when selected is
// empty or all names are known.
func validateSelectedTools(selected []string, tools config.MapOfTools) error {
	if len(selected) == 0 {
		return nil
	}
	var notFound []string
	for _, name := range selected {
		if _, ok := tools[name]; !ok {
			notFound = append(notFound, name)
		}
	}
	if len(notFound) == 0 {
		return nil
	}
	available := make([]string, 0, len(tools))
	for name := range tools {
		available = append(available, name)
	}
	sort.Strings(available)
	return &tooling.ToolNotFoundError{NotFound: notFound, Available: available}
}

// toolsWithoutGeneratedConfig returns the sorted subset of selected tools for
// which setup produced no config file — either because no config is associated
// with the tool, or because every associated config was skipped (e.g. its
// projectTypes did not match this location). It is derived from the actual
// install results so project-type skips are surfaced too, not just missing
// associations. Returns nil when no tools were selected.
func toolsWithoutGeneratedConfig(selected []string, configs config.MapOfConfigSetup, results []install.InstallResult) []string {
	if len(selected) == 0 {
		return nil
	}
	generated := make(map[string]bool)
	for _, r := range results {
		if r.Action == "" || r.Action == "skipped" {
			continue
		}
		ci, ok := configs[r.ConfigName]
		if !ok {
			continue
		}
		for _, t := range ci.Tools {
			generated[t] = true
		}
	}
	var none []string
	for _, t := range selected {
		if !generated[t] {
			none = append(none, t)
		}
	}
	sort.Strings(none)
	return none
}

// deduplicateGitRootResults removes duplicate results for git-root scoped configs.
// When multiple project locations produce results for the same FilePath and all
// have Scope="git-root", only one result is kept. If any result in the group has an
// error, the first error result is preferred so errors are never silently dropped.
func deduplicateGitRootResults(results []install.InstallResult) []install.InstallResult {
	type group struct {
		indices    []int
		allGitRoot bool
	}

	groups := make(map[string]*group)
	var order []string

	for i, r := range results {
		g, exists := groups[r.FilePath]
		if !exists {
			g = &group{allGitRoot: true}
			groups[r.FilePath] = g
			order = append(order, r.FilePath)
		}
		g.indices = append(g.indices, i)
		if r.Scope != config.ScopeGitRoot {
			g.allGitRoot = false
		}
	}

	keep := make(map[int]bool)
	for _, path := range order {
		g := groups[path]
		if g.allGitRoot && len(g.indices) > 1 {
			bestIdx := g.indices[0]
			for _, idx := range g.indices {
				if results[idx].Error != nil {
					bestIdx = idx
					break
				}
			}
			keep[bestIdx] = true
		} else {
			for _, idx := range g.indices {
				keep[idx] = true
			}
		}
	}

	var deduped []install.InstallResult
	for i, r := range results {
		if keep[i] {
			deduped = append(deduped, r)
		}
	}

	return deduped
}

// buildOptInIgnoreContent generates canonical .datamitsuignore content that
// disables every configured tool via a single catch-all rule (the opt-in
// model). Tool names are sorted for deterministic, lint-stable output. It
// returns the generated content and the number of tools listed. When there are
// no tools, it returns an empty string and a count of 0.
func buildOptInIgnoreContent(tools config.MapOfTools) (string, int) {
	if len(tools) == 0 {
		return "", 0
	}

	names := make([]string, 0, len(tools))
	for name := range tools {
		names = append(names, name)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("# Generated by `datamitsu setup --opt-in-tools`.\n")
	b.WriteString("# All configured tools are disabled by default (opt-in model).\n")
	b.WriteString("# Enable a tool by removing it from the list below (or add \"!**/*: <tool>\").\n")
	b.WriteString("**/*: ")
	b.WriteString(strings.Join(names, ", "))
	b.WriteString("\n")

	return b.String(), len(names)
}

// ensureNoExistingIgnore guards against clobbering a manually maintained
// .datamitsuignore. It returns an error if the file already exists at rootPath
// (so opt-in tool selections are never silently lost), nil when it is absent,
// and surfaces any other stat error.
func ensureNoExistingIgnore(rootPath string) error {
	path := filepath.Join(rootPath, optInIgnoreFilename)
	_, err := os.Stat(path)
	if err == nil {
		return fmt.Errorf("%s already exists at %s; refusing to overwrite (remove it first to regenerate)", optInIgnoreFilename, rootPath)
	}
	if os.IsNotExist(err) {
		return nil
	}
	return fmt.Errorf("failed to stat %s: %w", path, err)
}

// writeOptInIgnore generates an all-disabled .datamitsuignore at rootPath listing
// every configured tool (the opt-in model). With no tools it writes nothing and
// prints an info line. In dry-run mode it reports intent without touching the
// filesystem; in real mode it writes the file with 0o644 permissions.
func writeOptInIgnore(rootPath string, tools config.MapOfTools, dryRun bool) error {
	content, count := buildOptInIgnoreContent(tools)
	if count == 0 {
		ui.Current().PhaseBody(clr.Faint("no configured tools to disable; skipping .datamitsuignore"))
		return nil
	}

	path := filepath.Join(rootPath, optInIgnoreFilename)

	if dryRun {
		ui.Current().PhaseBody(clr.Green("+") + " " + optInIgnoreFilename + clr.Faint(fmt.Sprintf(" (would disable %d tools)", count)))
		return nil
	}

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("failed to write %s: %w", path, err)
	}
	ui.Current().PhaseBody(clr.Green("+") + " " + optInIgnoreFilename + clr.Faint(fmt.Sprintf(" (%d tools disabled)", count)))
	return nil
}

func buildConfigLinksRegistry(apps binmanager.MapOfApps, bundles binmanager.MapOfBundles) map[string]string {
	registry := make(map[string]string)
	for appName, app := range apps {
		for linkName := range app.Links {
			registry[linkName] = appName
		}
	}
	for bundleName, bundle := range bundles {
		if bundle == nil {
			continue
		}
		for linkName := range bundle.Links {
			registry[linkName] = bundleName
		}
	}
	return registry
}
