jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-environment
        with:
          setup-go: "false"

      - env:
          NODE_ENV: production
        name: Build website
        run: pnpm --filter website build

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./website/build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Deploy to GitHub Pages
    needs: build
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5

name: Deploy Website

on:
  push:
    branches:
      - main
  workflow_dispatch: {}
