jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-environment
        with:
          setup-go: "false"
      - env:
          NODE_ENV: production
        name: Test build website
        run: pnpm --filter website build
name: Test Website Build
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
