jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-environment
        with:
          setup-go: "false"

      - env:
          NODE_ENV: production
        name: Test build website
        run: pnpm --filter website build

name: Test Website Build

on:
  pull_request:
    branches:
      - main
